openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/cv-discovery/uolGlobaQueryComponents/1.0.0
    # Auto mocking server function (delete and replace with <servers: []>)
info:
  description: A global component-based API for querying genomic and biomedical data
  version: "1.0.0"
  title: UoL Global Query API Specification
  contact:
    email: uol.admin@cafevariome.org
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
# tags:
#   - name: admins
#     description: Secured Admin-only calls
#   - name: developers
#     description: Operations available to regular developers

paths:
  /query:
    post:
      summary: Make a search query with any combination of the components listed.
      operationId: postQuery
      description: 'Make a complex query by combining the available components and defining the correct query structure with a simple query string expresses in the form of boolean logic. e.g. (A AND B) OR C'
      parameters:
      - $ref: '#/components/schemas/subjectVariant'
      - $ref: '#/components/schemas/phenotype'
      - $ref: '#/components/schemas/gene'
      - $ref: '#/components/schemas/region'
      - $ref: '#/components/schemas/transcript'
      - $ref: '#/components/schemas/tissue'
      - $ref: '#/components/schemas/subject'
      - $ref: '#/components/schemas/demographics'
      - $ref: '#/components/schemas/sample'
      - $ref: '#/components/schemas/variantconsequence'
      - $ref: '#/components/schemas/genotype'
      - $ref: '#/components/schemas/booleanLogic'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/subjectVariant'
        '400':
          description: Unsuccessful response
          content:
            text/plain:
              schema:
                title: Not found

components:
  schemas:
    booleanLogic:
      description: Boolean operators "AND" and "OR" may be used to define the way in which components should be combined. Support for boolean logic operators are optional.
      type: object
      properties:
        queryString:
          type: string
          example: A AND (B OR C)

    subjectVariant:
      type: object
      properties:
        componentID:
          type: string
        name:
          type: string
          example: rs8179178
          description: An identifier for this variant e.g. rs id
        source:
          type: string
          example: dbSNP
          description: The source of the identifier used in name parameter
        hgvs:
          type: string
          example: NM_000088.3:c.589G>T
          description: HGVS Nomenclature
        allele:
          type: string
          pattern: ^([ATCGN]+)$
        genomebuild:
          type: string
          example: GRCh38
          description: The genome build cordinates for this variant are based on e.g. Grch38
        chromosome:
          type: string
          example: 1,X,Y,MT
          pattern: ^(\d{1,2}|[XY]|MT)$
          description: Reference name (chromosome). Accepting values 1-22, X, Y, MT
        range:
          type: string
          example: 1:6635137-6635325
          description: A comma separated list of genomic ranges in zero-based half open format, chromosome:start-end
        referenceBases:
          type: string
          pattern: ^([ATCGN]+)$
          example: G
          description: VCF-style reference alleles for this variant. At least one base.
        alternateBases:
          type: string
          example: C
          pattern: ^([ATCGN]+)$
          description: VCF-style alternate alleles for this variant. At least one base but can be ".".
        mutationType:
          type: string
          example: SNV,INDEL
          description: Type of variant mutation
        frequency:
          type: integer
          example: 0.25
          description:
        variantinheritance:
          type: string
          example: maternal
          description: From which parent(s) was the variant inherited or was it de novo
        origin:
          type: string
          example: germline
          description: Is the variant germline or somatic in origin in this subject. Default should be germline.
        pathogenic:
          type: string
          example: pathogenic, non-pathogenic
          description: Whether this variant was causal for the phenotype
        zygosity:
          type: string
          example: heterozygous
          description: Zygosity of the variant in this subject
        start:
          type: integer
          example: 1234567
          description: The start coordinate of the variant in the genome
        end:
          type: integer
          example: 1234570
          description:

    # subjectCopynumbervariant:
    #   type: object
    #   properties:
    #     componentID:
    #       type: string
    #     name:
    #       type: string
    #       example:
    #
    # subjectStructuralvariant:
    #   type: object
    #   properties:
    #     componentID:
    #       type: string
    #       example:
    #       description:

    gene:
      type: object
      properties:
        componentID:
          type: string
        name:
          type: string
          example: BRCA2
          description: Gene name
        hgncID:
          type: string
          example: HGNC:1101
          description: Hugo Gene Nomenclature Committee
        geneSource:
          type: string
          example: refseq
          description: search for genes of a specific source (Ensembl, refseq)

    transcript:
      type: object
      properties:
        componentID:
          type: string
        transcriptid:
          type: name
          example: NM_000527.1
        transcriptsource:
          type: string
          example: refseq
          description: The source of the transcript i.e. RefSeq or Ensembl

    phenotype:
      type: object
      properties:
        componentID:
          type: string
        termID:
          type: string
          example: HP:0040273
          description: Human Phenotype Ontology term IDs
        termName:
          type: string
          example: adenocarcinoma
          description: Human Phenotype Ontology term names
        source:
          type: string
          example: HPO
          description: The ontology from which the term id and name are sourced e.g. HPO, DiseaseOntology
        ageOfOnset:
          type: integer
          format: int64
          description: An HPO id of a term that represents a descendant of HP:0003674 "Clinical Course / Onset" or alternatives thereof.
        negated:
          type: boolean
          description: For use primarily with HPO queries that support it to indicate phenotype has been tested for and determined not to be present in the subject. This differs from term not being listed in HPO terms for this subject but whether the subject has the phenotype is underdetermined. Default is false.

    region:
      type: object
      properties:
        componentID:
          type: string
        regionType:
          type: string
          example: genome
          description: Type of region
        build:
          type: string
          example: GRCH38
          description: Genome build version
        start:
          type: integer
          format: int64
          minimum: 0
          example: 686554151
          description: Start position of chromosome region
        end:
          type: integer
          example: 686555948
          description: End position of chromosome region

    tissue:
      type: object
      properties:
        componentID:
          type: string
        tissuetype:
          type: string
          description: The tissue/organ/
        timesampled:
          type: string
          description: The date-time that the sample was taken

    subject:
      type: object
      properties:
        componentID:
          type: string
        subjectid:
          type: string

    demographics:
      type: object
      properties:
        componentID:
          type: string
        age:
          type:: integer
          description:
        sex:
          type: string
          description: PATO term describing biological sex of the subject

    sample:
      type: object
      properties:
        componentID:
          type: string
        sampleid:
          type: string

    variantconsequence:
      type: object
      properties:
        componentID:
          type: string
        consequenceType:
          type: string
          example: missense_variant, non_synonymous
          description: Type of consequence in sequence ontology format

    genotype:
      type: object
      properties:
        componentID:
          type: string
        genotype:
          type: string
